### ISSUE TITLE
/polls page has no background picture

### ISSUE THREAD

**Issue by knilios** [Jangsoodlor/ku-polls#13]
![image](https://github.com/user-attachments/assets/fb3a41d9-43b0-466e-89a6-92b5b58643b8)
This ```/polls``` page has no background image.

**Comment by Jangsoodlor** [comment]
fixed at this commit
https://github.com/Jangsoodlor/ku-polls/commit/dd37f21dec33b9aa8b5d70d0b1b350aefbe9fa21
